In [8]:
import regex as re
import os
import torch

from collections import Counter
from multiprocessing import Pool
from typing import BinaryIO, List, Tuple, Dict
from cs336_basics.linear import Linear

In [9]:
linear = Linear(3, 5)

In [13]:
linear.W.data

tensor([[-0.1342,  0.1989,  0.6613, -0.6585,  1.0053],
        [ 0.4055,  0.7231, -0.3705, -0.0217, -1.1310],
        [ 0.3800, -0.4722, -0.0909,  0.3299,  0.0280]])

In [15]:
x = torch.randn(5, 3)

In [16]:
x

tensor([[ 0.4133, -1.1972, -0.2141],
        [-0.2992, -1.0914, -1.8551],
        [ 0.9451,  0.3591, -0.0554],
        [ 0.8127, -1.0617, -1.6412],
        [-0.6643, -1.7629,  0.6284]])

In [25]:
token_ids = torch.tensor(
    [[0, 2, 4],
    [1, 2, 3]]
)

In [26]:
token_ids

tensor([[0, 2, 4],
        [1, 2, 3]])

In [27]:
x[token_ids]

tensor([[[ 0.4133, -1.1972, -0.2141],
         [ 0.9451,  0.3591, -0.0554],
         [-0.6643, -1.7629,  0.6284]],

        [[-0.2992, -1.0914, -1.8551],
         [ 0.9451,  0.3591, -0.0554],
         [ 0.8127, -1.0617, -1.6412]]])